Explicitly signal stream initiation and termination
jumpstarter-dev/jumpstarter-python pull request #29
Opened 2024-08-01 15:23 UTC by NickCao

2024-08-06 11:16 UTC, mangelajo commented on jumpstarter/drivers/base.py
> +                # small resources might be fully buffered in memory
What do you mean by this?

2024-08-06 11:44 UTC, mangelajo requested changes
Looks great, just some comments about logging all "pass calls"

2024-08-06 11:44 UTC, mangelajo commented on jumpstarter/common/streams.py
> +        pass
we are doing excessive use of pass , in some cases we should at least log it (warning), which will help in the future if issues arise from it.

2024-08-06 11:44 UTC, mangelajo commented on jumpstarter/common/streams.py
>                  pass
same here.

2024-08-06 11:44 UTC, mangelajo commented on jumpstarter/common/streams.py
> +                    pass
see my comments on pass.

2024-08-06 13:00 UTC, NickCao commented on jumpstarter/drivers/base.py
> +                # small resources might be fully buffered in memory
Sequence of event:
1. client opens a stream for sharing resource
2. exporter accepts the stream and registers the other end of the stream and a resource
3. exporter starts task to forward data from the client side of the stream to the exporter side of the stream
3.1 (actually happened) stream is copied into internal buffer before being consumed, forward tasks exits, resource unregistered
4. driver get the stream from the dict and begins consuming the stream
4.1 (actually happened) driver fails to find resource
6. (originally intended) stream is fully consumed by the driver, forward tasks exits, resource unregistered

2024-08-06 13:01 UTC, NickCao commented on jumpstarter/drivers/base.py
> +                # small resources might be fully buffered in memory
TLDR: resource shouldn't be unregistered when forwarding task exits, but only when it's fully consumed (or client decides to cancel)

2024-08-06 13:03 UTC, NickCao commented on jumpstarter/common/streams.py
> +        pass
Opted for debug level, warning is too strong for these (expected to happen in daily use) errors.

2024-08-07 05:27 UTC, mangelajo commented on jumpstarter/drivers/base.py
> +                # small resources might be fully buffered in memory
Thanks for the explanation I see now :-)

2024-08-07 05:28 UTC, mangelajo approved these changes

2024-08-07 05:28 UTC, merged